"""Patch all GUI textures to use a unified red energy bar fill gradient at UV (176, 0)."""
from PIL import Image
import os

GD = os.path.join("d:\\MCMODDING\\tachyon\\src\\main\\resources\\assets\\tachyon\\textures\\gui")

# GUIs that have an energy bar fill at (176, 0) to (191, 51)
GUI_FILES = [
    "accelerator_controller.png",
    "thorium_reactor.png",
    "photon_compressor.png",
    # These are regenerated by their own scripts, but patch them too for safety
    "singularity_controller.png",
    "ore_crusher.png",
    "alloy_forge.png",
    "void_miner.png",
    "condenser_controller.png",
]

def patch_energy_bar(filepath):
    img = Image.open(filepath).convert("RGBA")
    pixels = img.load()
    for y in range(52):
        t = y / 51.0  # 0 at top (full), 1 at bottom (empty)
        r = int(200 + 55 * (1 - t))
        g = int(30 + 20 * t)
        b = int(30 + 20 * t)
        for x in range(176, 192):
            pixels[x, y] = (r, g, b, 255)
    img.save(filepath)

if __name__ == "__main__":
    print("Patching energy bar fills to unified red gradient...")
    for filename in GUI_FILES:
        filepath = os.path.join(GD, filename)
        if os.path.exists(filepath):
            patch_energy_bar(filepath)
            print(f"  Patched {filename}")
        else:
            print(f"  SKIP {filename} (not found)")
    print("Done!")
